const GRADE_ORDER = ["pre-k", "k", "1", "2", "3", "4", "5", "6", "7", "8", "11"];

const GRADE_LABELS = {
  "pre-k": "Pre-K",
  k: "Kindergarten",
  1: "1st Grade",
  2: "2nd Grade",
  3: "3rd Grade",
  4: "4th Grade",
  5: "5th Grade",
  6: "6th Grade",
  7: "7th Grade",
  8: "8th Grade",
  11: "11th Grade",
};

const GRADE_INFO = {
  "pre-k": { rit: 174, performing: "2nd–3rd grade level", topics: "Multiplication facts, basic fractions, coordinate pairs", globalPct: "55%" },
  k: { rit: 190.5, performing: "3rd–4th grade level", percentile: "99th", topics: "Unit rates, algebraic expressions, angle types", globalPct: "65%" },
  1: { rit: 206.6, performing: "5th–6th grade level", percentile: "99th", topics: "Mean/median/mode, y-intercepts, 3D nets, volume", globalPct: "75%" },
  2: { rit: 213.2, performing: "6th–7th grade level", percentile: "99th", topics: "Slope, joint probability, square roots, circumference", globalPct: "82%" },
  3: { rit: 220.7, performing: "7th–8th grade level", percentile: "99th", topics: "Quadratic graphing, cube roots, inequalities", globalPct: "87%" },
  4: { rit: 227.1, performing: "7th–8th grade level", percentile: "99th", topics: "Absolute value equations, transversals, line of best fit", globalPct: "91%" },
  5: { rit: 230, performing: "8th–9th grade level", percentile: "93rd–98th", topics: "FOIL, logarithms, Pythagorean theorem, factoring", globalPct: "93%" },
  6: { rit: 243.6, performing: "10th–11th grade level", percentile: "99th", topics: "Inverse trig, completing the square, radians", globalPct: "96.5%" },
  7: { rit: 253.7, performing: "11th–12th / Pre-Calc", percentile: "99th", topics: "Complex numbers, limits, Law of Sines, series", globalPct: "98.5%" },
  8: { rit: 258.2, performing: "12th grade / AP-ready", percentile: "99th", topics: "Parametric equations, induction, polar coordinates", globalPct: "99%" },
  11: { rit: 278.3, performing: "College-level / AP Calculus", percentile: "99th", topics: "Taylor series, eigenvalues, convergence, integrals", globalPct: "99.7%" },
};

const QUESTIONS = [
  // ═══════════════════════════════════════════════
  //  1ST GRADE  —  RIT 206.6  (~5th–6th grade)
  // ═══════════════════════════════════════════════

  {
    id: 11,
    grade: "1",
    type: "multiple-choice",
    answerIndex: 1,
    subject: "Algebra",
    question: "The equation is $y = 3x + 5$. What is the $y$-intercept?",
    options: ["3", "5", "8", "15"],
    answer: "5",
    calc: "none",
    isObscure: true,
    context:
      "First graders identifying y-intercepts from linear equations. Most schools introduce this in 8th grade.",
  },
  {
    id: 12,
    grade: "1",
    type: "multiple-choice",
    answerIndex: 0,
    subject: "Geometry",
    question: "Which net folds into a rectangular prism?",
    options: [
      "6 connected rectangles in a cross shape",
      "4 triangles joined to a square",
      "2 circles and 1 rectangle",
      "5 squares in an L-shape",
    ],
    answer: "6 connected rectangles in a cross shape",
    calc: "none",
    isObscure: true,
    context: "Visualizing 2D nets that fold into 3D solids — strong spatial reasoning at RIT 207.",
  },
  {
    id: 13,
    grade: "1",
    type: "free-response",
    subject: "Statistics",
    question: "Scores: 88, 91, 85, 90, 42. Identify the outlier.",
    answer: "42",
    acceptedAnswers: ["42"],
    calc: "none",
    isObscure: true,
    context: "Identifying outliers and their effect on the mean — most curricula place this in 6th–7th grade.",
  },
  {
    id: 14,
    grade: "1",
    type: "free-response",
    subject: "Statistics",
    question: "Find the mean (average) of: 12, 15, 14, 12, 17",
    answer: "14",
    acceptedAnswers: ["14"],
    calc: "none",
    isObscure: false,
    context:
      "Measures of central tendency — well-known. At RIT 207 students compute all three fluently.",
  },
  {
    id: 15,
    grade: "1",
    type: "free-response",
    subject: "Geometry",
    question:
      "A box is 5 cm long, 3 cm wide, and 4 cm tall. What is the volume in cubic centimeters?",
    answer: "60",
    acceptedAnswers: ["60"],
    calc: "none",
    isObscure: false,
    context: "V = l × w × h — one of the most recognizable geometry formulas.",
  },

  // ═══════════════════════════════════════════════
  //  3RD GRADE  —  RIT 220.7  (~7th–8th grade)
  // ═══════════════════════════════════════════════

  {
    id: 21,
    grade: "3",
    type: "free-response",
    subject: "Logarithms",
    question: "If $2^5 = 32$, then $\\log_2(32) = ?$",
    answer: "5",
    acceptedAnswers: ["5"],
    calc: "none",
    isObscure: true,
    context:
      "Logarithms in 3rd grade — inverse of exponentiation. The 221–230 band introduces log concepts.",
  },
  {
    id: 22,
    grade: "3",
    type: "free-response",
    subject: "Functions",
    question: "$f(x) = \\begin{cases} 2x + 1 & \\text{if } x < 3 \\\\ x^2 & \\text{if } x \\geq 3 \\end{cases}$. Find $f(2)$.",
    answer: "5",
    acceptedAnswers: ["5"],
    calc: "none",
    isObscure: true,
    context: "Evaluating piecewise functions — typically Algebra 2 / Pre-Calc content.",
  },
  {
    id: 23,
    grade: "3",
    type: "free-response",
    subject: "Probability",
    question: "$60\\%$ of a class plays sports. Of those, $40\\%$ also play an instrument. What percent of the whole class does both?",
    answer: "24",
    acceptedAnswers: ["24", "24%"],
    calc: "none",
    isObscure: true,
    context: "Conditional probability — most schools cover this in AP Statistics.",
  },
  {
    id: 24,
    grade: "3",
    type: "free-response",
    subject: "Geometry",
    question:
      "A right triangle has legs of length 5 and 12. What is the length of the hypotenuse?",
    answer: "13",
    acceptedAnswers: ["13"],
    calc: "none",
    isObscure: false,
    context: "a² + b² = c² — one of the most famous formulas in math.",
  },
  {
    id: 25,
    grade: "3",
    type: "free-response",
    subject: "Algebra",
    question: "Solve the inequality: $2x - 3 > 7$. $x > ?$",
    answer: "5",
    acceptedAnswers: ["5"],
    calc: "none",
    isObscure: false,
    context:
      "Solving and graphing inequalities — well-recognized algebra at this level.",
  },

  // ═══════════════════════════════════════════════
  //  5TH GRADE  —  RIT 230  (~8th–9th grade)
  // ═══════════════════════════════════════════════

  {
    id: 31,
    grade: "5",
    type: "multiple-choice",
    answerIndex: 0,
    subject: "Algebra",
    question: "Multiply using FOIL: $(x + 4)(x - 3) = ?$",
    options: [
      "$x^2 + x - 12$",
      "$x^2 - x - 12$",
      "$x^2 + 7x - 12$",
      "$x^2 + x + 12$",
    ],
    answer: "x² + x − 12",
    calc: "none",
    isObscure: true,
    context:
      "FOILing binomials — standard Algebra 1 content in the 231–240 band.",
  },
  {
    id: 32,
    grade: "5",
    type: "multiple-choice",
    answerIndex: 0,
    subject: "Logarithms",
    question: "Rewrite in logarithmic form: $5^3 = 125$",
    options: [
      "$\\log_5(125) = 3$",
      "$\\log_3(125) = 5$",
      "$\\log_5(3) = 125$",
      "$\\log_{125}(5) = 3$",
    ],
    answer: "log₅(125) = 3",
    calc: "none",
    isObscure: true,
    context: "Converting between exponential and log forms — Pre-Calculus content.",
  },
  {
    id: 33,
    grade: "5",
    type: "multiple-choice",
    answerIndex: 0,
    subject: "Functions",
    question: "What is the vertex of $y = |x - 2| + 3$?",
    options: ["$(2, 3)$", "$(-2, 3)$", "$(3, 2)$", "$(2, -3)$"],
    answer: "(2, 3)",
    calc: "none",
    isObscure: true,
    context: "Graphing absolute value functions with transformations — Algebra 2 content.",
  },
  {
    id: 34,
    grade: "5",
    type: "free-response",
    subject: "Geometry",
    question:
      "A 10-foot ladder leans against a wall. The base is 6 feet from the wall. How high up the wall does the ladder reach? (in feet)",
    answer: "8",
    acceptedAnswers: ["8"],
    calc: "none",
    isObscure: false,
    context:
      "The Pythagorean Theorem applied to a real-world problem at this level.",
  },
  {
    id: 35,
    grade: "5",
    type: "multiple-choice",
    answerIndex: 0,
    subject: "Algebra",
    question: "Factor completely: $x^2 - 7x + 12$",
    options: [
      "$(x - 3)(x - 4)$",
      "$(x + 3)(x - 4)$",
      "$(x - 2)(x - 6)$",
      "$(x + 3)(x + 4)$",
    ],
    answer: "(x − 3)(x − 4)",
    calc: "none",
    isObscure: false,
    context: "Factoring trinomials — recognizable Algebra 1 at RIT 230.",
  },

  // ═══════════════════════════════════════════════
  //  7TH GRADE  —  RIT 253.7  (~11th–12th / Pre-Calc)
  // ═══════════════════════════════════════════════

  {
    id: 41,
    grade: "7",
    type: "multiple-choice",
    answerIndex: 0,
    subject: "Algebra",
    question: "For $2x^3 - 3x^2 - 8x + 12 = 0$, which is an actual rational root?",
    options: ["$x = 2$", "$x = 5$", "$x = -4$", "$x = 7$"],
    answer: "x = 2",
    calc: "none",
    isObscure: true,
    context: "The rational root theorem is Pre-Calc. 7th graders cracking higher-degree polynomials.",
  },
  {
    id: 42,
    grade: "7",
    type: "multiple-choice",
    answerIndex: 0,
    subject: "Complex Numbers",
    question: "Simplify: $(3 + 2i)(4 - i)$ where $i^2 = -1$",
    options: ["$14 + 5i$", "$12 + 5i$", "$14 - 5i$", "$10 + 5i$"],
    answer: "14 + 5i",
    calc: "none",
    isObscure: true,
    context:
      "Complex number arithmetic in 7th grade. The 251–260 band introduces imaginary numbers.",
  },
  {
    id: 43,
    grade: "7",
    type: "free-response",
    subject: "Calculus Intro",
    question:
      "What is $\\lim_{x \\to 2} \\frac{x^2 - 4}{x - 2}$? (Hint: factor the numerator first.)",
    answer: "4",
    acceptedAnswers: ["4"],
    calc: "none",
    isObscure: true,
    context:
      "Intro to limits — the foundation of calculus — at the top of the 251–260+ zone.",
  },
  {
    id: 44,
    grade: "7",
    type: "multiple-choice",
    answerIndex: 0,
    subject: "Trigonometry",
    question: "Triangle $ABC$: $\\angle A = 40^\\circ$, $\\angle B = 60^\\circ$, side $a = 10$. Using the Law of Sines, find side $b$ (rounded to 1 decimal).",
    options: ["$\\approx 13.5$", "$\\approx 10.0$", "$\\approx 8.7$", "$\\approx 15.2$"],
    answer: "≈ 13.5",
    calc: "graphing",
    isObscure: false,
    context: "Law of Sines — well-known trig for non-right triangles.",
  },
  {
    id: 45,
    grade: "7",
    type: "multiple-choice",
    answerIndex: 0,
    subject: "Sequences",
    question:
      "Find the sum of the first 8 terms: $3, 6, 12, 24, \\ldots$",
    options: ["765", "384", "512", "1530"],
    answer: "765",
    calc: "scientific",
    isObscure: false,
    context:
      "Geometric series sums — students apply S = a(1 − rⁿ)/(1 − r).",
  },

  // ═══════════════════════════════════════════════
  //  11TH GRADE  —  RIT 278.3  (College / AP Calc)
  // ═══════════════════════════════════════════════

  {
    id: 51,
    grade: "11",
    type: "multiple-choice",
    answerIndex: 0,
    subject: "Calculus",
    question: "What are the first 4 terms of the Maclaurin series for $e^x$?",
    options: [
      "$1 + x + \\frac{x^2}{2} + \\frac{x^3}{6}$",
      "$1 + x + x^2 + x^3$",
      "$x + \\frac{x^2}{2} + \\frac{x^3}{3} + \\frac{x^4}{4}$",
      "$1 + 2x + 3x^2 + 4x^3$",
    ],
    answer: "1 + x + x²/2 + x³/6",
    calc: "none",
    isObscure: true,
    context:
      "Taylor/Maclaurin series — AP Calc BC / college math.",
  },
  {
    id: 52,
    grade: "11",
    type: "multiple-choice",
    answerIndex: 0,
    subject: "Linear Algebra",
    question: "For matrix $A = \\begin{bmatrix} 4 & 1 \\\\ 2 & 3 \\end{bmatrix}$, find the eigenvalues by solving $\\det(A - \\lambda I) = 0$.",
    options: [
      "$\\lambda = 2$ and $\\lambda = 5$",
      "$\\lambda = 1$ and $\\lambda = 6$",
      "$\\lambda = 3$ and $\\lambda = 4$",
      "$\\lambda = -2$ and $\\lambda = 5$",
    ],
    answer: "λ = 2 and λ = 5",
    calc: "none",
    isObscure: true,
    context: "Linear algebra eigenvalues — typically a college sophomore course.",
  },
  {
    id: 53,
    grade: "11",
    type: "multiple-choice",
    answerIndex: 1,
    subject: "Calculus",
    question: "Which infinite series converges?",
    options: [
      "$\\sum_{n=1}^{\\infty} \\frac{1}{n}$",
      "$\\sum_{n=1}^{\\infty} \\frac{1}{n^2}$",
      "$\\sum_{n=1}^{\\infty} n$",
      "$\\sum_{n=1}^{\\infty} \\frac{1}{\\sqrt{n}}$",
    ],
    answer: "Σ(1/n²) from n=1 to ∞",
    calc: "none",
    isObscure: true,
    context: "Convergence/divergence of series — core AP Calc BC / college analysis.",
  },
  {
    id: 54,
    grade: "11",
    type: "multiple-choice",
    answerIndex: 0,
    subject: "Calculus",
    question: "Find $f'(x)$ for $f(x) = 3x^4 - 2x^2 + 7x - 1$.",
    options: [
      "$12x^3 - 4x + 7$",
      "$12x^3 - 4x^2 + 7$",
      "$3x^3 - 2x + 7$",
      "$12x^4 - 4x^2 + 7x$",
    ],
    answer: "12x³ − 4x + 7",
    calc: "none",
    isObscure: false,
    context: "Power rule differentiation — bread-and-butter calculus.",
  },
  {
    id: 55,
    grade: "11",
    type: "free-response",
    subject: "Calculus",
    question: "Evaluate: $\\int_0^3 x^2 \\, dx$",
    answer: "9",
    acceptedAnswers: ["9"],
    calc: "none",
    isObscure: false,
    context:
      "Definite integrals via the Fundamental Theorem — well-known calculus.",
  },
];
